# Generated by Django 5.2.15 on 2026-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('device_type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('IN_USE', 'Em uso'), ('MAINTENANCE', 'Em manutenção')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('location', models.CharField(max_length=255, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
