# Generated by Django 4.2.30 on 2026-06-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('utensil_type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em uso', 'Em uso'), ('Manutenção', 'Manutenção')], default='Disponível', max_length=20, verbose_name='Status')),
                ('location', models.CharField(max_length=200, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utensílio',
                'verbose_name_plural': 'Utensílios',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Em uso', 'Em uso'), ('Manutenção', 'Manutenção')], default='Disponível', max_length=20, verbose_name='Status'),
        ),
    ]
