# Generated by Django 4.2.30 on 2026-06-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_utensil_alter_device_options_alter_device_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utensil',
            name='status',
        ),
        migrations.AddField(
            model_name='utensil',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
